config/routes.rb
Chargen::Application.routes.draw do
  resources :characters
  resources :races
  root "high_voltage/pages#show", id: 'home'
  devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)

    if user.has_role? :user
        can :manage, Character, :user => user
    end

    if user.has_role? :admin
        can :manage, Race
    elsif user.has_role? :user
        can [:index, :show], Race
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities
  end
end

app/models/character.rb
class Character < ActiveRecord::Base
	belongs_to :user
	belongs_to :race

	def new_ability_scores
		scores = []
		6.times do
			roll = []
				5.times do
					roll.push(rand(1...7))
				end
			roll.sort!.reverse!
			roll.pop
			roll.pop
			scores.push roll.reduce(:+)
		end
		return scores.sort!.reverse!
	end
end

app/models/race.rb
class Race < ActiveRecord::Base
	has_many :characters

	def modifiers
		abilities = {"STR" => self.str_adjust,"CON" => self.con_adjust, "DEX" => self.dex_adjust,"INT" => self.int_adjust,"WIS" => self.wis_adjust, "CHR" => self.chr_adjust}
		abilities.reject! {|key,value| value == 0 || value == nil }
		mods = []
		abilities.each do |key,value|
			mods << "#{key}: #{value}"
		end
		return mods
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :characters
	after_create :add_user_role

	private
		def add_user_role
			self.add_role :user
			self.save
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  load_and_authorize_resource

  # GET /characters
  # GET /characters.json
  def index
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)
    @character.user_id = current_user.id

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :eye_color, :hair_color, :height, :weight, :description, :race_id)
    end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  load_and_authorize_resource

  # GET /races
  # GET /races.json
  def index
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params[:race]
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	after_create :add_user_role

	private
		def add_user_role
			self.add_role :user
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/characters/_form.html.haml
= simple_form_for(@character) do |f|
  .form_group
    .row
      = f.error_notification
  .form_group
    .row
      .col-md-4
        = f.input :name
      .col-md-4
        = f.association :race
  %hr
  .form_group
    .row
      .col-md-1
        = f.input :strength
        = f.input :dexterity
        = f.input :constitution
        = f.input :intelligence
        = f.input :wisdom
        = f.input :charisma
      - if @character.new_record?
        .col-md-4
          %p Ability Scores:
          - @character.new_ability_scores.each do |s|
            %p
              = s

  %hr
  .form_group
    .row
      .col-md-3
        = f.input :eye_color
      .col-md-3
        = f.input :hair_color
      .col-md-3
        = f.input :height
      .col-md-3
        = f.input :weight
    .row
      .col-md-12
        = f.input :description
  %hr
  .row
    .form_group.col-md-12
      = f.button :submit

app/views/characters/edit.html.haml
%h1 Editing character

= render 'form'

= link_to 'Show', @character
\|
= link_to 'Back', characters_path

app/views/characters/index.html.haml
%h1 Listing characters
- if @characters.empty?
  %p
    You haven't made a character yet.
    %br
    = link_to "Create your first Character", new_character_path, class: "btn btn-primary"
-else
  %ul
  - @characters.each do |character|
    %li
      %p
      = link_to character.name, character
      \-
      = link_to 'Edit', edit_character_path(character)
      = link_to 'Destroy', character, :method => :delete, :data => { :confirm => 'Are you sure?' }
  = link_to "New Character", new_character_path, class: "btn btn-primary"

app/views/characters/new.html.haml
%h1 New character

= render 'form'

= link_to 'Back', characters_path

app/views/characters/show.html.haml
%h1
	= @character.name
%p
	%b Player:
	= @character.user.name
%p
	%b Race:
	= @character.race.name
%h2 Stats
%dl.dl-horizontal
	%dt STR:
	%dd
		= @character.strength
	%dt CON:
	%dd
		= @character.constitution
	%dt DEX:
	%dd
		= @character.dexterity
	%dt INT:
	%dd
		= @character.intelligence
	%dt WIS:
	%dd
		= @character.wisdom
	%dt CHA:
	%dd
		= @character.charisma
%h2 Description
%dl
	%dt Hair Color:
	%dd
		= @character.hair_color
	%dt Eye Color:
	%dd
		= @character.eye_color
	%dt Height:
	%dd
		= @character.height
	%dt Weight:
	%dd
		= @character.weight
	%dt Description:
	%dd
		= @character.description



= link_to 'Edit', edit_character_path(@character)
\|
= link_to 'Back', characters_path

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to "Logged in as: #{current_user.name}" , edit_user_registration_path %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'My Characters', characters_path %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Chargen'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Chargen'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        .row-md-12
          = render 'layouts/messages'
          = yield

app/views/pages/home.html.haml
%h1 Pathfinder Char Gen
- unless current_user.has_role? :user
	%p
		= link_to "Sign In", new_user_session_path
		\- or -
		= link_to "Sign Up", new_user_registration_path

app/views/races/_form.html.haml
= simple_form_for(@race) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/races/edit.html.haml
%h1 Editing race

= render 'form'

= link_to 'Show', @race
\|
= link_to 'Back', races_path

app/views/races/index.html.haml
%h1 Races

- @races.each do |race|
  = link_to race.name.titleize, race
  = link_to 'Edit', edit_race_path(race)
  = link_to 'Destroy', race, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Race', new_race_path

app/views/races/new.html.haml
%h1 New race

= render 'form'

= link_to 'Back', races_path

app/views/races/show.html.haml
%h1= @race.name.titleize
%p= @race.description
%h2 Ability Modifiers
%ul
-	@race.modifiers.each do |m|
	%li= m
%p
	= link_to 'Edit', edit_race_path(@race)
	\|
	= link_to 'Back', races_path